---
title: "primula_VR_model_selection"
author: "JL"
date: "`r Sys.Date()`"
output: html_document
---


```{r packages}
library(tidyverse)
library(AICcmodavg)
library(lme4)
library(patchwork)

theme_set(theme_classic()) #for ggplot
```



```{r sourcing data}
# Read in data ------------------------------------------------------------------------

### read in all years of Primula data and weather data from the Cowichan
# Add in climate data:
climate_scale <- read.csv("C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/Primula/data_for_publication/CGOP_climatevalues_scaled.csv")

# Add in demography data:
primula <- read.csv("C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/Primula/data_for_publication/Primula_Demography_Data_2016to2023.csv")

## Join climate data to demography data by year
primula <- left_join(primula, climate_scale, by = "year") %>%
  mutate(pflower = as.factor(pflower),
         pflowerT1 = as.factor(pflowerT1),
         psurvivalT1 = as.factor(psurvivalT1))

remove(climate_scale)
```


We've settled on: Winter, summer, and spring mean temp; and spring precip
```{r growth candidate models}
# Candidate models
## sans climate
gm.base.size <- lmer(log.ros.areaT1 ~ log.ros.area + (1|plot) + (1|year), data = primula, REML = F)
gm.base.trt <- lmer(log.ros.areaT1 ~ log.ros.area + trt + (1|plot) + (1|year), data = primula, REML = F)
gm.base.trt.int <- lmer(log.ros.areaT1 ~ log.ros.area*trt + (1|plot) + (1|year), data = primula, REML = F)
gm.base.cor <- lmer(log.ros.areaT1 ~ log.ros.area + pflower + (1|plot) + (1|year), data = primula, REML = F)
gm.base.cor.int <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + (1|plot) + (1|year), data = primula, REML = F)
gm.base.cor.trt <- lmer(log.ros.areaT1 ~ log.ros.area + trt + pflower + (1|plot) + (1|year), data = primula, REML = F)
gm.base.cor.trt.int1 <- lmer(log.ros.areaT1 ~ log.ros.area*trt + pflower + (1|plot) + (1|year), data = primula, REML = F)
gm.base.cor.trt.int2 <- lmer(log.ros.areaT1 ~ log.ros.area + trt*pflower + (1|plot) + (1|year), data = primula, REML = F)
gm.base.cor.trt.int3 <- lmer(log.ros.areaT1 ~ log.ros.area*trt*pflower + (1|plot) + (1|year), data = primula, REML = F)

#the rest of the models below are just these + different climate variables + interactions
########################################################################################
##grow season total precip
gm.gs.precip <- lmer(log.ros.areaT1 ~ log.ros.area + spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.int <- lmer(log.ros.areaT1 ~ log.ros.area*spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)

gm.gs.precip.trt <- lmer(log.ros.areaT1 ~ log.ros.area + spring.tot.precip + trt + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.trt.int1 <- lmer(log.ros.areaT1 ~ log.ros.area*spring.tot.precip + trt + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.trt.int2 <- lmer(log.ros.areaT1 ~ log.ros.area + spring.tot.precip*trt + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.trt.int3 <- lmer(log.ros.areaT1 ~ log.ros.area*spring.tot.precip*trt + (1|plot) + (1|year), data = primula, REML = F)

gm.gs.precip.cor <- lmer(log.ros.areaT1 ~ log.ros.area + pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.int1 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.int2 <- lmer(log.ros.areaT1 ~ log.ros.area + pflower*spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.int3 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower*spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)

gm.gs.precip.cor.trt <- lmer(log.ros.areaT1 ~ log.ros.area + trt + pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.trt.int1 <- lmer(log.ros.areaT1 ~ log.ros.area*trt + pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.trt.int2 <- lmer(log.ros.areaT1 ~ log.ros.area + trt*pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.trt.int3 <- lmer(log.ros.areaT1 ~ log.ros.area + pflower + trt*spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.trt.int4 <- lmer(log.ros.areaT1 ~ log.ros.area + trt + pflower*spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.trt.int5 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + trt +  spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.trt.int6 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + trt*spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.trt.int7 <- lmer(log.ros.areaT1 ~ log.ros.area*trt + pflower*spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.trt.int8 <- lmer(log.ros.areaT1 ~ log.ros.area*spring.tot.precip + pflower*trt  + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.trt.int9 <- lmer(log.ros.areaT1 ~ log.ros.area*spring.tot.precip + pflower + trt + (1|plot) + (1|year), data = primula, REML = F)

gm.gs.precip.cor.trt.int10 <- lmer(log.ros.areaT1 ~ log.ros.area*spring.tot.precip*pflower + trt + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.trt.int11 <- lmer(log.ros.areaT1 ~ log.ros.area + spring.tot.precip*pflower*trt + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.trt.int12 <- lmer(log.ros.areaT1 ~ log.ros.area*trt*spring.tot.precip + pflower + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.precip.cor.trt.int13 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower*trt + spring.tot.precip + (1|plot) + (1|year), data = primula, REML = F)



###
#grow season ave temp
gm.gs.av.temp <- lmer(log.ros.areaT1 ~ log.ros.area + spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.int <- lmer(log.ros.areaT1 ~ log.ros.area*spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)

gm.gs.av.temp.trt <- lmer(log.ros.areaT1 ~ log.ros.area + spring.mean.temp + trt + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.trt.int1 <- lmer(log.ros.areaT1 ~ log.ros.area*spring.mean.temp + trt + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.trt.int2 <- lmer(log.ros.areaT1 ~ log.ros.area + spring.mean.temp*trt + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.trt.int3 <- lmer(log.ros.areaT1 ~ log.ros.area*spring.mean.temp*trt + (1|plot) + (1|year), data = primula, REML = F)

gm.gs.av.temp.cor <- lmer(log.ros.areaT1 ~ log.ros.area + pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.int1 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.int2 <- lmer(log.ros.areaT1 ~ log.ros.area + pflower*spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.int3 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower*spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)

gm.gs.av.temp.cor.trt <- lmer(log.ros.areaT1 ~ log.ros.area + trt + pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.trt.int1 <- lmer(log.ros.areaT1 ~ log.ros.area*trt + pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.trt.int2 <- lmer(log.ros.areaT1 ~ log.ros.area + trt*pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.trt.int3 <- lmer(log.ros.areaT1 ~ log.ros.area + pflower + trt*spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.trt.int4 <- lmer(log.ros.areaT1 ~ log.ros.area + trt + pflower*spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.trt.int5 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + trt +  spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.trt.int6 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + trt*spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.trt.int7 <- lmer(log.ros.areaT1 ~ log.ros.area*trt + pflower*spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.trt.int8 <- lmer(log.ros.areaT1 ~ log.ros.area*spring.mean.temp + pflower*trt  + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.trt.int9 <- lmer(log.ros.areaT1 ~ log.ros.area*spring.mean.temp + pflower + trt + (1|plot) + (1|year), data = primula, REML = F)

gm.gs.av.temp.cor.trt.int10 <- lmer(log.ros.areaT1 ~ log.ros.area*spring.mean.temp*pflower + trt + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.trt.int11 <- lmer(log.ros.areaT1 ~ log.ros.area + spring.mean.temp*pflower*trt + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.trt.int12 <- lmer(log.ros.areaT1 ~ log.ros.area*trt*spring.mean.temp + pflower + (1|plot) + (1|year), data = primula, REML = F)
gm.gs.av.temp.cor.trt.int13 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower*trt + spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)

###
#summer ave temp
gm.summer.av.temp <- lmer(log.ros.areaT1 ~ log.ros.area + summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.int <- lmer(log.ros.areaT1 ~ log.ros.area*summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)

gm.summer.av.temp.trt <- lmer(log.ros.areaT1 ~ log.ros.area + summer.mean.temp + trt + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.trt.int1 <- lmer(log.ros.areaT1 ~ log.ros.area*summer.mean.temp + trt + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.trt.int2 <- lmer(log.ros.areaT1 ~ log.ros.area + summer.mean.temp*trt + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.trt.int3 <- lmer(log.ros.areaT1 ~ log.ros.area*summer.mean.temp*trt + (1|plot) + (1|year), data = primula, REML = F)

gm.summer.av.temp.cor <- lmer(log.ros.areaT1 ~ log.ros.area + pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.int1 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.int2 <- lmer(log.ros.areaT1 ~ log.ros.area + pflower*summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.int3 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower*summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)

gm.summer.av.temp.cor.trt <- lmer(log.ros.areaT1 ~ log.ros.area + trt + pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.trt.int1 <- lmer(log.ros.areaT1 ~ log.ros.area*trt + pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.trt.int2 <- lmer(log.ros.areaT1 ~ log.ros.area + trt*pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.trt.int3 <- lmer(log.ros.areaT1 ~ log.ros.area + pflower + trt*summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.trt.int4 <- lmer(log.ros.areaT1 ~ log.ros.area + trt + pflower*summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.trt.int5 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + trt +  summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.trt.int6 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + trt*summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.trt.int7 <- lmer(log.ros.areaT1 ~ log.ros.area*trt + pflower*summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.trt.int8 <- lmer(log.ros.areaT1 ~ log.ros.area*summer.mean.temp + pflower*trt  + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.trt.int9 <- lmer(log.ros.areaT1 ~ log.ros.area*summer.mean.temp + pflower + trt + (1|plot) + (1|year), data = primula, REML = F)

gm.summer.av.temp.cor.trt.int10 <- lmer(log.ros.areaT1 ~ log.ros.area*summer.mean.temp*pflower + trt + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.trt.int11 <- lmer(log.ros.areaT1 ~ log.ros.area + summer.mean.temp*pflower*trt + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.trt.int12 <- lmer(log.ros.areaT1 ~ log.ros.area*trt*summer.mean.temp + pflower + (1|plot) + (1|year), data = primula, REML = F)
gm.summer.av.temp.cor.trt.int13 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower*trt + summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)

###
#winter ave temp
gm.winter.av.temp <- lmer(log.ros.areaT1 ~ log.ros.area + winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.int <- lmer(log.ros.areaT1 ~ log.ros.area*winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)

gm.winter.av.temp.trt <- lmer(log.ros.areaT1 ~ log.ros.area + winter.mean.temp + trt + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.trt.int1 <- lmer(log.ros.areaT1 ~ log.ros.area*winter.mean.temp + trt + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.trt.int2 <- lmer(log.ros.areaT1 ~ log.ros.area + winter.mean.temp*trt + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.trt.int3 <- lmer(log.ros.areaT1 ~ log.ros.area*winter.mean.temp*trt + (1|plot) + (1|year), data = primula, REML = F)

gm.winter.av.temp.cor <- lmer(log.ros.areaT1 ~ log.ros.area + pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.int1 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.int2 <- lmer(log.ros.areaT1 ~ log.ros.area + pflower*winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.int3 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower*winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)

gm.winter.av.temp.cor.trt <- lmer(log.ros.areaT1 ~ log.ros.area + trt + pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.trt.int1 <- lmer(log.ros.areaT1 ~ log.ros.area*trt + pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.trt.int2 <- lmer(log.ros.areaT1 ~ log.ros.area + trt*pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.trt.int3 <- lmer(log.ros.areaT1 ~ log.ros.area + pflower + trt*winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.trt.int4 <- lmer(log.ros.areaT1 ~ log.ros.area + trt + pflower*winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.trt.int5 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + trt +  winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.trt.int6 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + trt*winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.trt.int7 <- lmer(log.ros.areaT1 ~ log.ros.area*trt + pflower*winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.trt.int8 <- lmer(log.ros.areaT1 ~ log.ros.area*winter.mean.temp + pflower*trt  + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.trt.int9 <- lmer(log.ros.areaT1 ~ log.ros.area*winter.mean.temp + pflower + trt + (1|plot) + (1|year), data = primula, REML = F)

gm.winter.av.temp.cor.trt.int10 <- lmer(log.ros.areaT1 ~ log.ros.area*winter.mean.temp*pflower + trt + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.trt.int11 <- lmer(log.ros.areaT1 ~ log.ros.area + winter.mean.temp*pflower*trt + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.trt.int12 <- lmer(log.ros.areaT1 ~ log.ros.area*trt*winter.mean.temp + pflower + (1|plot) + (1|year), data = primula, REML = F)
gm.winter.av.temp.cor.trt.int13 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower*trt + winter.mean.temp + (1|plot) + (1|year), data = primula, REML = F)

################################################################################
###
growth <- mget(ls(pattern = "^gm")) #make a list of all of those models that start with gm (^ means start with)
growth_AICc<-aictab(cand.set = growth, modnames = NULL,second.ord=TRUE,nobs=NULL,sort=TRUE)

#rm(list = ls()[grepl("gm", ls())]) #removes everything with gm
gm.summer.av.temp.cor.trt.int6 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + trt*summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
summary(gm.summer.av.temp.cor.trt.int6)

#saving AIC table:
## names of models:
# names <- as.data.frame(names(growth))
# growth_AICc <- growth_AICc %>% 
#   arrange(Modnames)
# 
# names=data.frame(model.names = c(1:105))
# growth_AICc$model.names[[i]]
# 
# for (i in 1:105) {
#     names$formulas[[i]]<- formula(growth[[i]])
#     names$formulas <- names$formulas
# }

AIC.save <- growth_AICc %>% 
  arrange(AICc) %>% 
  slice_head(n =10)
AIC.save$vitalrate <- "growth"

```

```{r}
# best fit:
gm.summer.av.temp.cor.trt.int6 <- lmer(log.ros.areaT1 ~ log.ros.area*pflower + trt*summer.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
summary(gm.summer.av.temp.cor.trt.int6)
```

Figure for growth:

```{r}
pred.dat <- expand.grid(
  log.ros.area = seq(min(primula$log.ros.area, na.rm = TRUE), max(primula$log.ros.area, na.rm = TRUE), by = .1), 
  summer.mean.temp = c(-1, 0, 1), 
  pflower = c("0","1"), 
  trt = c("irrigated", "control", "drought"))
pred.dat.output.g <- cbind(pred.dat, log.ros.areaT1 = predict(gm.summer.av.temp.cor.trt.int6, newdata = pred.dat, type = "response", re.form = ~0))

(irrgrowth <- ggplot(data = subset(primula, !is.na(pflower) & trt == "irrigated"), aes(x = log.ros.area, y = log.ros.areaT1))+
  geom_point(alpha= 0.2, shape = 1)+
  geom_abline(slope=1, intercept = 0, color= "black", linewidth = .2)+
  geom_line(data = subset(pred.dat.output.g, trt == "irrigated"), aes(x = log.ros.area, y = log.ros.areaT1, color = as.character(summer.mean.temp), linetype = pflower),linewidth = 1.25)+
  scale_color_manual(values = c("#323697", "#94c8e0", "#f2623f"), name = "Temp.")+
  scale_linetype_manual(values=c("dotted", "solid"), labels = c("vegetative", "flowered"), name = "") +  
  scale_y_continuous(expand = c(0, 0), limits = c(0, 6))+
  scale_x_continuous(expand = c(0, 0), limits = c(0, 6))+  
  labs(x = "log(Rosette Area) in t", y = "log(Rosette Area) in t + 1", title = "Irrigated")+
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), 
        text = element_text(size = 20), 
        plot.title = element_text(vjust = - 5, hjust = .03, colour = "#2892c7")))

  #annotate("text",x = .75, y = 5.75, label = "a) irrigated")#+ 
#theme(legend.position="none")

#ggsave(plot = irrgrowth, file = "C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/Primula/Figures/climate vital rate selection/growth irr.png", width = 6, height = 6, dpi = 300)
(cgrowth <- ggplot(data = subset(primula, !is.na(pflower) & trt == "control"), aes(x = log.ros.area, y = log.ros.areaT1))+
  geom_point(alpha= 0.2, shape = 1)+
  geom_abline(slope=1, intercept = 0, color= "black", linewidth = .2)+
  geom_line(data = subset(pred.dat.output.g, trt == "control"), aes(x = log.ros.area, y = log.ros.areaT1, color = as.character(summer.mean.temp), linetype = pflower),linewidth = 1.25)+
  scale_color_manual(values = c("#323697", "#94c8e0", "#f2623f"), name = "Temp.")+
  scale_linetype_manual(values=c("dotted", "solid"), labels = c("vegetative", "flowered"), name = "") +  
  scale_y_continuous(expand = c(0, 0), limits = c(0, 6))+
  scale_x_continuous(expand = c(0, 0), limits = c(0, 6))+  
  labs(x = "log(Rosette Area) in t", y = "log(Rosette Area) in t + 1", title = "Control")+
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), 
        text = element_text(size = 20), 
        plot.title = element_text(vjust = - 5, hjust = .03, colour = "#5f9034")))
#ggsave(plot = cgrowth, file = "C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/Primula/Figures/climate vital rate selection/growth control.png", width = 6, height = 6, dpi = 300)

(drgrowth <- ggplot(data = subset(primula, !is.na(pflower) & trt == "drought"), aes(x = log.ros.area, y = log.ros.areaT1))+
  geom_point(alpha= 0.2, shape = 1)+
  geom_abline(slope=1, intercept = 0, color= "black", linewidth = .2)+
  geom_line(data = subset(pred.dat.output.g, trt == "drought"), aes(x = log.ros.area, y = log.ros.areaT1, color = as.character(summer.mean.temp), linetype = pflower),linewidth = 1.25)+
  scale_color_manual(values = c("#323697", "#94c8e0", "#f2623f"), name = "Temp.")+
  scale_linetype_manual(values=c("dotted", "solid"), labels = c("vegetative", "flowered"), name = "") +  
  scale_y_continuous(expand = c(0, 0), limits = c(0, 6))+
  scale_x_continuous(expand = c(0, 0), limits = c(0, 6))+  
  labs(x = "log(Rosette Area) in t", y = "log(Rosette Area) in t + 1", title = "Drought")+
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), 
        text = element_text(size = 20), 
        plot.title = element_text(vjust = - 5, hjust = .03, colour = "#e81014")))
#ggsave(plot = drgrowth, file = "C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/Primula/Figures/climate vital rate selection/growth drought.png", width = 6, height = 6, dpi = 300)

#patch these together
(together <- irrgrowth + cgrowth +  drgrowth + plot_layout(guides = "collect", axis_titles = "collect", ncol = 3)+plot_annotation(tag_level = "A"))
ggsave(plot = together, file = "C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/Primula/Figures/climate vital rate selection/growthVR 2-16.png", width = 16, height = 6, dpi = 300)

```
```{r}
#size difference for these:
#largest flowering plant: 5.798690
#smallest flowering plant: 1.955660
#percentiles
quant <- primula %>%  
  summarize(perc10 = quantile(log.ros.area, probs = 0.10, na.rm = T),
            perc90 = quantile(log.ros.area, probs = 0.90, na.rm = T))
pred.dat <- expand.grid(
  log.ros.area = c(2.379474, 4.728249), #10th and 90th perc)
  summer.mean.temp = c(-1, 0, 1), 
  pflower = c("0","1"), 
  trt = c("irrigated", "control", "drought"))
pred.dat.output.g <- cbind(pred.dat, log.ros.areaT1 = predict(gm.summer.av.temp.cor.trt.int6, newdata = pred.dat, type = "response", re.form = ~0))

comp <- pred.dat.output.g %>% 
  mutate(ros.areaT1 = exp(log.ros.areaT1))
  
```

###

```{r pflower candidate models}
# Candidate models
## without climate
### anything commented out is a model that doesnt converge
fm.base <- glmer(pflowerT1 ~ 1 + (1|plot) + (1|year), data = primula, family = "binomial")
fm.base.size <- glmer(pflowerT1 ~ log.ros.area + (1|plot) + (1|year), data = primula, family = "binomial")
fm.base.trt <- glmer(pflowerT1 ~ log.ros.area + trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.base.trt.int <- glmer(pflowerT1 ~ log.ros.area*trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.base.cor <- glmer(pflowerT1 ~ log.ros.area + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
fm.base.cor.int <- glmer(pflowerT1 ~ log.ros.area*pflower + (1|plot) + (1|year), data = primula, family = "binomial")
fm.base.cor.trt <- glmer(pflowerT1 ~ log.ros.area + trt + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
fm.base.cor.trt.int1 <- glmer(pflowerT1 ~ log.ros.area*trt + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
fm.base.cor.trt.int2 <- glmer(pflowerT1 ~ log.ros.area + trt*pflower + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.base.cor.trt.int3 <- glmer(pflowerT1 ~ log.ros.area*trt*pflower + (1|plot) + (1|year), data = primula, family = "binomial")

#the rest of the models below are just these + different climate variables + interactions
########################################################################################
##spring  total precip
fm.gs.precip <- glmer(pflowerT1 ~ log.ros.area + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.precip.int <- glmer(pflowerT1 ~ log.ros.area*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")

fm.gs.precip.trt <- glmer(pflowerT1 ~ log.ros.area + spring.tot.precip + trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.precip.trt.int1 <- glmer(pflowerT1 ~ log.ros.area*spring.tot.precip + trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.precip.trt.int2 <- glmer(pflowerT1 ~ log.ros.area + spring.tot.precip*trt + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.precip.trt.int3 <- glmer(pflowerT1 ~ log.ros.area*spring.tot.precip*trt + (1|plot) + (1|year), data = primula, family = "binomial")

fm.gs.precip.cor <- glmer(pflowerT1 ~ log.ros.area + pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.precip.cor.int1 <- glmer(pflowerT1 ~ log.ros.area*pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.precip.cor.int2 <- glmer(pflowerT1 ~ log.ros.area + pflower*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.precip.cor.int3 <- glmer(pflowerT1 ~ log.ros.area*pflower*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")

fm.gs.precip.cor.trt <- glmer(pflowerT1 ~ log.ros.area + trt + pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.precip.cor.trt.int1 <- glmer(pflowerT1 ~ log.ros.area*trt + pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.precip.cor.trt.int2 <- glmer(pflowerT1 ~ log.ros.area + trt*pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.precip.cor.trt.int3 <- glmer(pflowerT1 ~ log.ros.area + pflower + trt*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.precip.cor.trt.int4 <- glmer(pflowerT1 ~ log.ros.area + trt + pflower*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
##fm.gs.precip.cor.trt.int5 <- glmer(pflowerT1 ~ log.ros.area*pflower + trt +  spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.precip.cor.trt.int6 <- glmer(pflowerT1 ~ log.ros.area*pflower + trt*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.precip.cor.trt.int7 <- glmer(pflowerT1 ~ log.ros.area*trt + pflower*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.precip.cor.trt.int8 <- glmer(pflowerT1 ~ log.ros.area*spring.tot.precip + pflower*trt  + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.precip.cor.trt.int9 <- glmer(pflowerT1 ~ log.ros.area*spring.tot.precip + pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")

#fm.gs.precip.cor.trt.int10 <- glmer(pflowerT1 ~ log.ros.area*spring.tot.precip*pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.precip.cor.trt.int11 <- glmer(pflowerT1 ~ log.ros.area + spring.tot.precip*pflower*trt + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.precip.cor.trt.int12 <- glmer(pflowerT1 ~ log.ros.area*trt*spring.tot.precip + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.precip.cor.trt.int13 <- glmer(pflowerT1 ~ log.ros.area*pflower*trt + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")

###
#spring ave temp
fm.gs.av.temp <- glmer(pflowerT1 ~ log.ros.area + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.av.temp.int <- glmer(pflowerT1 ~ log.ros.area*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")

fm.gs.av.temp.trt <- glmer(pflowerT1 ~ log.ros.area + spring.mean.temp + trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.av.temp.trt.int1 <- glmer(pflowerT1 ~ log.ros.area*spring.mean.temp + trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.av.temp.trt.int2 <- glmer(pflowerT1 ~ log.ros.area + spring.mean.temp*trt + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.av.temp.trt.int3 <- glmer(pflowerT1 ~ log.ros.area*spring.mean.temp*trt + (1|plot) + (1|year), data = primula, family = "binomial")

fm.gs.av.temp.cor <- glmer(pflowerT1 ~ log.ros.area + pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.av.temp.cor.int1 <- glmer(pflowerT1 ~ log.ros.area*pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.av.temp.cor.int2 <- glmer(pflowerT1 ~ log.ros.area + pflower*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.av.temp.cor.int3 <- glmer(pflowerT1 ~ log.ros.area*pflower*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")

fm.gs.av.temp.cor.trt <- glmer(pflowerT1 ~ log.ros.area + trt + pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.av.temp.cor.trt.int1 <- glmer(pflowerT1 ~ log.ros.area*trt + pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.av.temp.cor.trt.int2 <- glmer(pflowerT1 ~ log.ros.area + trt*pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.av.temp.cor.trt.int3 <- glmer(pflowerT1 ~ log.ros.area + pflower + trt*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.av.temp.cor.trt.int4 <- glmer(pflowerT1 ~ log.ros.area + trt + pflower*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.av.temp.cor.trt.int5 <- glmer(pflowerT1 ~ log.ros.area*pflower + trt +  spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.av.temp.cor.trt.int6 <- glmer(pflowerT1 ~ log.ros.area*pflower + trt*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.av.temp.cor.trt.int7 <- glmer(pflowerT1 ~ log.ros.area*trt + pflower*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.av.temp.cor.trt.int8 <- glmer(pflowerT1 ~ log.ros.area*spring.mean.temp + pflower*trt  + (1|plot) + (1|year), data = primula, family = "binomial")
fm.gs.av.temp.cor.trt.int9 <- glmer(pflowerT1 ~ log.ros.area*spring.mean.temp + pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")

#fm.gs.av.temp.cor.trt.int10 <- glmer(pflowerT1 ~ log.ros.area*spring.mean.temp*pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.av.temp.cor.trt.int11 <- glmer(pflowerT1 ~ log.ros.area + spring.mean.temp*pflower*trt + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.av.temp.cor.trt.int12 <- glmer(pflowerT1 ~ log.ros.area*trt*spring.mean.temp + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.gs.av.temp.cor.trt.int13 <- glmer(pflowerT1 ~ log.ros.area*pflower*trt + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")

# ###
# #summer ave temp
fm.summer.av.temp <- glmer(pflowerT1 ~ log.ros.area + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.int <- glmer(pflowerT1 ~ log.ros.area*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
# 
fm.summer.av.temp.trt <- glmer(pflowerT1 ~ log.ros.area + summer.mean.temp + trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.trt.int1 <- glmer(pflowerT1 ~ log.ros.area*summer.mean.temp + trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.trt.int2 <- glmer(pflowerT1 ~ log.ros.area + summer.mean.temp*trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.trt.int3 <- glmer(pflowerT1 ~ log.ros.area*summer.mean.temp*trt + (1|plot) + (1|year), data = primula, family = "binomial")

fm.summer.av.temp.cor <- glmer(pflowerT1 ~ log.ros.area + pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.int1 <- glmer(pflowerT1 ~ log.ros.area*pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.int2 <- glmer(pflowerT1 ~ log.ros.area + pflower*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.int3 <- glmer(pflowerT1 ~ log.ros.area*pflower*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")

fm.summer.av.temp.cor.trt <- glmer(pflowerT1 ~ log.ros.area + trt + pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.trt.int1 <- glmer(pflowerT1 ~ log.ros.area*trt + pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.trt.int2 <- glmer(pflowerT1 ~ log.ros.area + trt*pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.trt.int3 <- glmer(pflowerT1 ~ log.ros.area + pflower + trt*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.trt.int4 <- glmer(pflowerT1 ~ log.ros.area + trt + pflower*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.trt.int5 <- glmer(pflowerT1 ~ log.ros.area*pflower + trt +  summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.trt.int6 <- glmer(pflowerT1 ~ log.ros.area*pflower + trt*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.trt.int7 <- glmer(pflowerT1 ~ log.ros.area*trt + pflower*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.trt.int8 <- glmer(pflowerT1 ~ log.ros.area*summer.mean.temp + pflower*trt  + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.trt.int9 <- glmer(pflowerT1 ~ log.ros.area*summer.mean.temp + pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")

fm.summer.av.temp.cor.trt.int10 <- glmer(pflowerT1 ~ log.ros.area*summer.mean.temp*pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.trt.int11 <- glmer(pflowerT1 ~ log.ros.area + summer.mean.temp*pflower*trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.trt.int12 <- glmer(pflowerT1 ~ log.ros.area*trt*summer.mean.temp + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
fm.summer.av.temp.cor.trt.int13 <- glmer(pflowerT1 ~ log.ros.area*pflower*trt + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")

# 
# ###############################################################################
# ###
#winter ave temp
fm.winter.av.temp <- glmer(pflowerT1 ~ log.ros.area + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.int <- glmer(pflowerT1 ~ log.ros.area*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")

fm.winter.av.temp.trt <- glmer(pflowerT1 ~ log.ros.area + winter.mean.temp + trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.trt.int1 <- glmer(pflowerT1 ~ log.ros.area*winter.mean.temp + trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.trt.int2 <- glmer(pflowerT1 ~ log.ros.area + winter.mean.temp*trt + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.winter.av.temp.trt.int3 <- glmer(pflowerT1 ~ log.ros.area*winter.mean.temp*trt + (1|plot) + (1|year), data = primula, family = "binomial")

fm.winter.av.temp.cor <- glmer(pflowerT1 ~ log.ros.area + pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.cor.int1 <- glmer(pflowerT1 ~ log.ros.area*pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.cor.int2 <- glmer(pflowerT1 ~ log.ros.area + pflower*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.winter.av.temp.cor.int3 <- glmer(pflowerT1 ~ log.ros.area*pflower*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")

fm.winter.av.temp.cor.trt <- glmer(pflowerT1 ~ log.ros.area + trt + pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.winter.av.temp.cor.trt.int1 <- glmer(pflowerT1 ~ log.ros.area*trt + pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.cor.trt.int2 <- glmer(pflowerT1 ~ log.ros.area + trt*pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.cor.trt.int3 <- glmer(pflowerT1 ~ log.ros.area + pflower + trt*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.cor.trt.int4 <- glmer(pflowerT1 ~ log.ros.area + trt + pflower*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.cor.trt.int5 <- glmer(pflowerT1 ~ log.ros.area*pflower + trt +  winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.cor.trt.int6 <- glmer(pflowerT1 ~ log.ros.area*pflower + trt*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.cor.trt.int7 <- glmer(pflowerT1 ~ log.ros.area*trt + pflower*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.cor.trt.int8 <- glmer(pflowerT1 ~ log.ros.area*winter.mean.temp + pflower*trt  + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.cor.trt.int9 <- glmer(pflowerT1 ~ log.ros.area*winter.mean.temp + pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")

#fm.winter.av.temp.cor.trt.int10 <- glmer(pflowerT1 ~ log.ros.area*winter.mean.temp*pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")
fm.winter.av.temp.cor.trt.int11 <- glmer(pflowerT1 ~ log.ros.area + winter.mean.temp*pflower*trt + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.winter.av.temp.cor.trt.int12 <- glmer(pflowerT1 ~ log.ros.area*trt*winter.mean.temp + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
#fm.winter.av.temp.cor.trt.int13 <- glmer(pflowerT1 ~ log.ros.area*pflower*trt + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")

###
flowering <- mget(ls(pattern = "^fm")) #make a list of all of those models that start with fm (^ means start with)
flowering_AICc<-aictab(cand.set = flowering, modnames = NULL,second.ord=TRUE,nobs=NULL,sort=TRUE)

#rm(list = ls()[grepl("fm", ls())]) #remove everything
#this is the best one that also converges
fm.gs.av.temp.cor.int1 <- glmer(pflowerT1 ~ log.ros.area*pflower +spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
summary(fm.gs.av.temp.cor.int1)

AIC.save.flow <- flowering_AICc %>% 
  arrange(AICc) %>% 
  slice_head(n =10)
AIC.save.flow$vitalrate <- "pflower"
AIC.save <- rbind(AIC.save, AIC.save.flow)
```

```{r best fit model}
fm.gs.av.temp.cor.int1 <- glmer(pflowerT1 ~ log.ros.area*pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
summary(fm.gs.av.temp.cor.int1)
```


```{r pflower figure}
#fm.gs.av.temp.cor.int1
pred.dat <- expand.grid(
  log.ros.area = seq(min(primula$log.ros.area, na.rm = TRUE), max(primula$log.ros.area, na.rm = TRUE), by = .1), 
  spring.mean.temp = c(-1, 0, 1), 
  pflower = c("0","1"))
pred.dat.output.f <- cbind(pred.dat, pflowerT1 = predict(fm.gs.av.temp.cor.int1, newdata = pred.dat, type = "response", re.form = ~0))

(pflow <- ggplot(subset(primula,!is.na(pflowerT1) & !is.na(pflower)), aes(x = log.ros.area, y = as.numeric(pflowerT1) - 1)) +
  geom_jitter(height = .025, alpha = 0.05) +
  geom_line(data = subset(pred.dat.output.f, pflower == "0" & spring.mean.temp == 0), aes(x = log.ros.area, y = pflowerT1), linetype = "dotted", color = "#94c8e0", size = 1.5) +
  geom_line(data = subset(pred.dat.output.f, pflower == "1" & spring.mean.temp == 0), aes(x = log.ros.area, y = pflowerT1), color = "#94c8e0", size = 1.5) +
  geom_line(data = subset(pred.dat.output.f, pflower == "0" & spring.mean.temp == 1), aes(x = log.ros.area, y = pflowerT1), linetype = "dotted", color = "#f2623f", size = 1.5) +
  geom_line(data = subset(pred.dat.output.f, pflower == "1" & spring.mean.temp == 1), aes(x = log.ros.area, y = pflowerT1), color = "#f2623f", size = 1.5) +
  geom_line(data = subset(pred.dat.output.f, pflower == "0" & spring.mean.temp == -1), aes(x = log.ros.area, y = pflowerT1), linetype = "dotted", color = "#323697", size = 1.5) +
  geom_line(data = subset(pred.dat.output.f, pflower == "1" & spring.mean.temp == -1), aes(x = log.ros.area, y = pflowerT1), color = "#323697", size = 1.5) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 6)) +
  labs(x = "log(Rosette Area) in t", y = "Probability of Flowering in t + 1") +
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), text = element_text(size = 20)))


#ggsave(plot = pflow, file = "C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/Primula/Figures/climate vital rate selection/5 gs temp flowering.png", width = 6, height = 6, dpi = 300)

```

#survival:
```{r survival candidate models}
# Candidate models
## sans climate
#commented out blocks are models that do not converge
#sm.base <- glmer(psurvivalT1 ~ 1 + (1|plot) + (1|year), data = primula, family = "binomial")
sm.base.size <- glmer(psurvivalT1 ~ log.ros.area + (1|plot) + (1|year), data = primula, family = "binomial")
sm.base.trt <- glmer(psurvivalT1 ~ log.ros.area + trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.base.trt.int <- glmer(psurvivalT1 ~ log.ros.area*trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.base.cor <- glmer(psurvivalT1 ~ log.ros.area + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
sm.base.cor.int <- glmer(psurvivalT1 ~ log.ros.area*pflower + (1|plot) + (1|year), data = primula, family = "binomial")
sm.base.cor.trt <- glmer(psurvivalT1 ~ log.ros.area + trt + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
sm.base.cor.trt.int1 <- glmer(psurvivalT1 ~ log.ros.area*trt + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
sm.base.cor.trt.int2 <- glmer(psurvivalT1 ~ log.ros.area + trt*pflower + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.base.cor.trt.int3 <- glmer(psurvivalT1 ~ log.ros.area*trt*pflower + (1|plot) + (1|year), data = primula, family = "binomial")
#the rest of the models below are just these + different climate variables + interactions
########################################################################################
##spring total precip
sm.gs.precip <- glmer(psurvivalT1 ~ log.ros.area + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.int <- glmer(psurvivalT1 ~ log.ros.area*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.trt <- glmer(psurvivalT1 ~ log.ros.area + spring.tot.precip + trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.trt.int1 <- glmer(psurvivalT1 ~ log.ros.area*spring.tot.precip + trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.trt.int2 <- glmer(psurvivalT1 ~ log.ros.area + spring.tot.precip*trt + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.gs.precip.trt.int3 <- glmer(psurvivalT1 ~ log.ros.area*spring.tot.precip*trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.cor <- glmer(psurvivalT1 ~ log.ros.area + pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.cor.int1 <- glmer(psurvivalT1 ~ log.ros.area*pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.cor.int2 <- glmer(psurvivalT1 ~ log.ros.area + pflower*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.gs.precip.cor.int3 <- glmer(psurvivalT1 ~ log.ros.area*pflower*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.cor.trt <- glmer(psurvivalT1 ~ log.ros.area + trt + pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.cor.trt.int1 <- glmer(psurvivalT1 ~ log.ros.area*trt + pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.cor.trt.int2 <- glmer(psurvivalT1 ~ log.ros.area + trt*pflower + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.cor.trt.int3 <- glmer(psurvivalT1 ~ log.ros.area + pflower + trt*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.cor.trt.int4 <- glmer(psurvivalT1 ~ log.ros.area + trt + pflower*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.cor.trt.int5 <- glmer(psurvivalT1 ~ log.ros.area*pflower + trt +  spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.gs.precip.cor.trt.int6 <- glmer(psurvivalT1 ~ log.ros.area*pflower + trt*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.cor.trt.int7 <- glmer(psurvivalT1 ~ log.ros.area*trt + pflower*spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.cor.trt.int8 <- glmer(psurvivalT1 ~ log.ros.area*spring.tot.precip + pflower*trt  + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.cor.trt.int9 <- glmer(psurvivalT1 ~ log.ros.area*spring.tot.precip + pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.gs.precip.cor.trt.int10 <- glmer(psurvivalT1 ~ log.ros.area*spring.tot.precip*pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.precip.cor.trt.int11 <- glmer(psurvivalT1 ~ log.ros.area + spring.tot.precip*pflower*trt + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.gs.precip.cor.trt.int12 <- glmer(psurvivalT1 ~ log.ros.area*trt*spring.tot.precip + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.gs.precip.cor.trt.int13 <- glmer(psurvivalT1 ~ log.ros.area*pflower*trt + spring.tot.precip + (1|plot) + (1|year), data = primula, family = "binomial")

###
#grow season ave temp
sm.gs.av.temp <- glmer(psurvivalT1 ~ log.ros.area + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.int <- glmer(psurvivalT1 ~ log.ros.area*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.trt <- glmer(psurvivalT1 ~ log.ros.area + spring.mean.temp + trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.trt.int1 <- glmer(psurvivalT1 ~ log.ros.area*spring.mean.temp + trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.trt.int2 <- glmer(psurvivalT1 ~ log.ros.area + spring.mean.temp*trt + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.gs.av.temp.trt.int3 <- glmer(psurvivalT1 ~ log.ros.area*spring.mean.temp*trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.cor <- glmer(psurvivalT1 ~ log.ros.area + pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.cor.int1 <- glmer(psurvivalT1 ~ log.ros.area*pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.cor.int2 <- glmer(psurvivalT1 ~ log.ros.area + pflower*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.gs.av.temp.cor.int3 <- glmer(psurvivalT1 ~ log.ros.area*pflower*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.cor.trt <- glmer(psurvivalT1 ~ log.ros.area + trt + pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.cor.trt.int1 <- glmer(psurvivalT1 ~ log.ros.area*trt + pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.cor.trt.int2 <- glmer(psurvivalT1 ~ log.ros.area + trt*pflower + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.cor.trt.int3 <- glmer(psurvivalT1 ~ log.ros.area + pflower + trt*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.cor.trt.int4 <- glmer(psurvivalT1 ~ log.ros.area + trt + pflower*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.cor.trt.int5 <- glmer(psurvivalT1 ~ log.ros.area*pflower + trt +  spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.gs.av.temp.cor.trt.int6 <- glmer(psurvivalT1 ~ log.ros.area*pflower + trt*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.cor.trt.int7 <- glmer(psurvivalT1 ~ log.ros.area*trt + pflower*spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.cor.trt.int8 <- glmer(psurvivalT1 ~ log.ros.area*spring.mean.temp + pflower*trt  + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.cor.trt.int9 <- glmer(psurvivalT1 ~ log.ros.area*spring.mean.temp + pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.gs.av.temp.cor.trt.int10 <- glmer(psurvivalT1 ~ log.ros.area*spring.mean.temp*pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.gs.av.temp.cor.trt.int11 <- glmer(psurvivalT1 ~ log.ros.area + spring.mean.temp*pflower*trt + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.gs.av.temp.cor.trt.int12 <- glmer(psurvivalT1 ~ log.ros.area*trt*spring.mean.temp + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.gs.av.temp.cor.trt.int13 <- glmer(psurvivalT1 ~ log.ros.area*pflower*trt + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")

#summer ave temp
sm.summer.av.temp <- glmer(psurvivalT1 ~ log.ros.area + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.int <- glmer(psurvivalT1 ~ log.ros.area*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.trt <- glmer(psurvivalT1 ~ log.ros.area + summer.mean.temp + trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.trt.int1 <- glmer(psurvivalT1 ~ log.ros.area*summer.mean.temp + trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.trt.int2 <- glmer(psurvivalT1 ~ log.ros.area + summer.mean.temp*trt + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.summer.av.temp.trt.int3 <- glmer(psurvivalT1 ~ log.ros.area*summer.mean.temp*trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.cor <- glmer(psurvivalT1 ~ log.ros.area + pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.cor.int1 <- glmer(psurvivalT1 ~ log.ros.area*pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.cor.int2 <- glmer(psurvivalT1 ~ log.ros.area + pflower*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.summer.av.temp.cor.int3 <- glmer(psurvivalT1 ~ log.ros.area*pflower*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.cor.trt <- glmer(psurvivalT1 ~ log.ros.area + trt + pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.summer.av.temp.cor.trt.int1 <- glmer(psurvivalT1 ~ log.ros.area*trt + pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.cor.trt.int2 <- glmer(psurvivalT1 ~ log.ros.area + trt*pflower + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.cor.trt.int3 <- glmer(psurvivalT1 ~ log.ros.area + pflower + trt*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.cor.trt.int4 <- glmer(psurvivalT1 ~ log.ros.area + trt + pflower*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.cor.trt.int5 <- glmer(psurvivalT1 ~ log.ros.area*pflower + trt +  summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.cor.trt.int6 <- glmer(psurvivalT1 ~ log.ros.area*pflower + trt*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.summer.av.temp.cor.trt.int7 <- glmer(psurvivalT1 ~ log.ros.area*trt + pflower*summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.cor.trt.int8 <- glmer(psurvivalT1 ~ log.ros.area*summer.mean.temp + pflower*trt  + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.cor.trt.int9 <- glmer(psurvivalT1 ~ log.ros.area*summer.mean.temp + pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.summer.av.temp.cor.trt.int10 <- glmer(psurvivalT1 ~ log.ros.area*summer.mean.temp*pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.summer.av.temp.cor.trt.int11 <- glmer(psurvivalT1 ~ log.ros.area + summer.mean.temp*pflower*trt + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.summer.av.temp.cor.trt.int12 <- glmer(psurvivalT1 ~ log.ros.area*trt*summer.mean.temp + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.summer.av.temp.cor.trt.int13 <- glmer(psurvivalT1 ~ log.ros.area*pflower*trt + summer.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")


###
#winter ave temp
sm.winter.av.temp <- glmer(psurvivalT1 ~ log.ros.area + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.int <- glmer(psurvivalT1 ~ log.ros.area*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.trt <- glmer(psurvivalT1 ~ log.ros.area + winter.mean.temp + trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.trt.int1 <- glmer(psurvivalT1 ~ log.ros.area*winter.mean.temp + trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.trt.int2 <- glmer(psurvivalT1 ~ log.ros.area + winter.mean.temp*trt + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.winter.av.temp.trt.int3 <- glmer(psurvivalT1 ~ log.ros.area*winter.mean.temp*trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor <- glmer(psurvivalT1 ~ log.ros.area + pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor.int1 <- glmer(psurvivalT1 ~ log.ros.area*pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor.int2 <- glmer(psurvivalT1 ~ log.ros.area + pflower*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.winter.av.temp.cor.int3 <- glmer(psurvivalT1 ~ log.ros.area*pflower*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor.trt <- glmer(psurvivalT1 ~ log.ros.area + trt + pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor.trt.int1 <- glmer(psurvivalT1 ~ log.ros.area*trt + pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor.trt.int2 <- glmer(psurvivalT1 ~ log.ros.area + trt*pflower + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor.trt.int3 <- glmer(psurvivalT1 ~ log.ros.area + pflower + trt*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor.trt.int4 <- glmer(psurvivalT1 ~ log.ros.area + trt + pflower*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor.trt.int5 <- glmer(psurvivalT1 ~ log.ros.area*pflower + trt +  winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.winter.av.temp.cor.trt.int6 <- glmer(psurvivalT1 ~ log.ros.area*pflower + trt*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor.trt.int7 <- glmer(psurvivalT1 ~ log.ros.area*trt + pflower*winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor.trt.int8 <- glmer(psurvivalT1 ~ log.ros.area*winter.mean.temp + pflower*trt  + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor.trt.int9 <- glmer(psurvivalT1 ~ log.ros.area*winter.mean.temp + pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.winter.av.temp.cor.trt.int10 <- glmer(psurvivalT1 ~ log.ros.area*winter.mean.temp*pflower + trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor.trt.int11 <- glmer(psurvivalT1 ~ log.ros.area + winter.mean.temp*pflower*trt + (1|plot) + (1|year), data = primula, family = "binomial")
sm.winter.av.temp.cor.trt.int12 <- glmer(psurvivalT1 ~ log.ros.area*trt*winter.mean.temp + pflower + (1|plot) + (1|year), data = primula, family = "binomial")
#sm.winter.av.temp.cor.trt.int13 <- glmer(psurvivalT1 ~ log.ros.area*pflower*trt + winter.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")

survival <- mget(ls(pattern = "^sm")) #make a list of all of those models that start with gm (^ means start with)
survival_AICc<-aictab(cand.set = survival, modnames = NULL,second.ord=TRUE,nobs=NULL,sort=TRUE)

#rm(list = ls()[grepl("sm", ls())])

#and it converges etc

AIC.save.surv <- survival_AICc %>% 
  arrange(AICc) %>% 
  slice_head(n =10)
AIC.save.surv$vitalrate <- "survival"
AIC.save <- rbind(AIC.save, AIC.save.surv)
```

```{r}
#best fit is:
sm.gs.av.temp <- glmer(psurvivalT1 ~ log.ros.area + spring.mean.temp + (1|plot) + (1|year), data = primula, family = "binomial")
summary(	sm.gs.av.temp)
```


#survival figure
```{r surv figure}
pred.dat <- expand.grid(
  log.ros.area = seq(min(primula$log.ros.area, na.rm = TRUE), max(primula$log.ros.area, na.rm = TRUE), by = .1), 
  spring.mean.temp = c(-1, 0, 1))
pred.dat.output.s <- cbind(pred.dat, survT1 = predict(sm.gs.av.temp, newdata = pred.dat, type = "response", re.form = ~0))


(survival <- 
  ggplot(subset(primula, !is.na(psurvivalT1)), aes(x = log.ros.area, y = as.numeric(psurvivalT1)-1))+
  geom_jitter(height = .025, alpha = 0.05) +
  geom_line(data = subset(pred.dat.output.s, spring.mean.temp == -1), aes(x = log.ros.area, y = survT1), color = "#323697", size = 1.5) +
  geom_line(data = subset(pred.dat.output.s, spring.mean.temp == 1), aes(x = log.ros.area, y = survT1), color = "#f2623f", size = 1.5) +
  geom_line(data = subset(pred.dat.output.s, spring.mean.temp == 0), aes(x = log.ros.area, y = survT1), color = "#94c8e0", size = 1.5) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 6))+
  labs(x = "log(Rosette Area) in t", y = "Survival in t+1")+
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), text = element_text(size = 20)))
survival
#ggsave(plot = survival, file = "C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/Primula/Figures/climate vital rate selection/2survival temp.fig.png", width = 6, height = 6, dpi = 300)

```

#no flowers
```{r model selection}
#commented out models do not converge
noflowers.base <- glmer(flow.sumT1 ~ 1 + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.base.size <- glmer(flow.sumT1 ~ log.ros.area + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.base.trt <- glmer(flow.sumT1 ~ log.ros.area + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.base.trt.int <- glmer(flow.sumT1 ~ log.ros.area*trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.base.cor <- glmer(flow.sumT1 ~ log.ros.area + pflower + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.base.cor.int <- glmer(flow.sumT1 ~ log.ros.area*pflower + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.base.cor.trt <- glmer(flow.sumT1 ~ log.ros.area + trt + pflower + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.base.cor.trt.int1 <- glmer(flow.sumT1 ~ log.ros.area*trt + pflower + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.base.cor.trt.int2 <- glmer(flow.sumT1 ~ log.ros.area + trt*pflower + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.base.cor.trt.int3 <- glmer(flow.sumT1 ~ log.ros.area*trt*pflower + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#the rest of the models below are just these + different climate variables + interactions
########################################################################################
##grow season total precip
noflowers.gs.precip <- glmer(flow.sumT1 ~ log.ros.area + spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.int <- glmer(flow.sumT1 ~ log.ros.area*spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

noflowers.gs.precip.trt <- glmer(flow.sumT1 ~ log.ros.area + spring.tot.precip + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.trt.int1 <- glmer(flow.sumT1 ~ log.ros.area*spring.tot.precip + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.trt.int2 <- glmer(flow.sumT1 ~ log.ros.area + spring.tot.precip*trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.precip.trt.int3 <- glmer(flow.sumT1 ~ log.ros.area*spring.tot.precip*trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

noflowers.gs.precip.cor <- glmer(flow.sumT1 ~ log.ros.area + pflower + spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.cor.int1 <- glmer(flow.sumT1 ~ log.ros.area*pflower + spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.cor.int2 <- glmer(flow.sumT1 ~ log.ros.area + pflower*spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.cor.int3 <- glmer(flow.sumT1 ~ log.ros.area*pflower*spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

noflowers.gs.precip.cor.trt <- glmer(flow.sumT1 ~ log.ros.area + trt + pflower + spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.precip.cor.trt.int1 <- glmer(flow.sumT1 ~ log.ros.area*trt + pflower + spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.cor.trt.int2 <- glmer(flow.sumT1 ~ log.ros.area + trt*pflower + spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.cor.trt.int3 <- glmer(flow.sumT1 ~ log.ros.area + pflower + trt*spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.cor.trt.int4 <- glmer(flow.sumT1 ~ log.ros.area + trt + pflower*spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.precip.cor.trt.int5 <- glmer(flow.sumT1 ~ log.ros.area*pflower + trt +  spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.cor.trt.int6 <- glmer(flow.sumT1 ~ log.ros.area*pflower + trt*spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.cor.trt.int7 <- glmer(flow.sumT1 ~ log.ros.area*trt + pflower*spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.precip.cor.trt.int8 <- glmer(flow.sumT1 ~ log.ros.area*spring.tot.precip + pflower*trt  + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.cor.trt.int9 <- glmer(flow.sumT1 ~ log.ros.area*spring.tot.precip + pflower + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

#noflowers.gs.precip.cor.trt.int10 <- glmer(flow.sumT1 ~ log.ros.area*spring.tot.precip*pflower + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.cor.trt.int11 <- glmer(flow.sumT1 ~ log.ros.area + spring.tot.precip*pflower*trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.precip.cor.trt.int12 <- glmer(flow.sumT1 ~ log.ros.area*trt*spring.tot.precip + pflower + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.precip.cor.trt.int13 <- glmer(flow.sumT1 ~ log.ros.area*pflower*trt + spring.tot.precip + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")



###
#grow season ave temp
noflowers.gs.av.temp <- glmer(flow.sumT1 ~ log.ros.area + spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.av.temp.int <- glmer(flow.sumT1 ~ log.ros.area*spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

noflowers.gs.av.temp.trt <- glmer(flow.sumT1 ~ log.ros.area + spring.mean.temp + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.av.temp.trt.int1 <- glmer(flow.sumT1 ~ log.ros.area*spring.mean.temp + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.av.temp.trt.int2 <- glmer(flow.sumT1 ~ log.ros.area + spring.mean.temp*trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.av.temp.trt.int3 <- glmer(flow.sumT1 ~ log.ros.area*spring.mean.temp*trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

noflowers.gs.av.temp.cor <- glmer(flow.sumT1 ~ log.ros.area + pflower + spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.av.temp.cor.int1 <- glmer(flow.sumT1 ~ log.ros.area*pflower + spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.av.temp.cor.int2 <- glmer(flow.sumT1 ~ log.ros.area + pflower*spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.av.temp.cor.int3 <- glmer(flow.sumT1 ~ log.ros.area*pflower*spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

noflowers.gs.av.temp.cor.trt <- glmer(flow.sumT1 ~ log.ros.area + trt + pflower + spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.av.temp.cor.trt.int1 <- glmer(flow.sumT1 ~ log.ros.area*trt + pflower + spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.av.temp.cor.trt.int2 <- glmer(flow.sumT1 ~ log.ros.area + trt*pflower + spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.av.temp.cor.trt.int3 <- glmer(flow.sumT1 ~ log.ros.area + pflower + trt*spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.gs.av.temp.cor.trt.int4 <- glmer(flow.sumT1 ~ log.ros.area + trt + pflower*spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.av.temp.cor.trt.int5 <- glmer(flow.sumT1 ~ log.ros.area*pflower + trt +  spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.av.temp.cor.trt.int6 <- glmer(flow.sumT1 ~ log.ros.area*pflower + trt*spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.av.temp.cor.trt.int7 <- glmer(flow.sumT1 ~ log.ros.area*trt + pflower*spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.av.temp.cor.trt.int8 <- glmer(flow.sumT1 ~ log.ros.area*spring.mean.temp + pflower*trt  + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.av.temp.cor.trt.int9 <- glmer(flow.sumT1 ~ log.ros.area*spring.mean.temp + pflower + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

#noflowers.gs.av.temp.cor.trt.int10 <- glmer(flow.sumT1 ~ log.ros.area*spring.mean.temp*pflower + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.av.temp.cor.trt.int11 <- glmer(flow.sumT1 ~ log.ros.area + spring.mean.temp*pflower*trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.av.temp.cor.trt.int12 <- glmer(flow.sumT1 ~ log.ros.area*trt*spring.mean.temp + pflower + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.gs.av.temp.cor.trt.int13 <- glmer(flow.sumT1 ~ log.ros.area*pflower*trt + spring.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

#########################################################################################
#summer ave temp
noflowers.summer.av.temp <- glmer(flow.sumT1 ~ log.ros.area + summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.summer.av.temp.int <- glmer(flow.sumT1 ~ log.ros.area*summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

noflowers.summer.av.temp.trt <- glmer(flow.sumT1 ~ log.ros.area + summer.mean.temp + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.summer.av.temp.trt.int1 <- glmer(flow.sumT1 ~ log.ros.area*summer.mean.temp + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.summer.av.temp.trt.int2 <- glmer(flow.sumT1 ~ log.ros.area + summer.mean.temp*trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.summer.av.temp.trt.int3 <- glmer(flow.sumT1 ~ log.ros.area*summer.mean.temp*trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

noflowers.summer.av.temp.cor <- glmer(flow.sumT1 ~ log.ros.area + pflower + summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.summer.av.temp.cor.int1 <- glmer(flow.sumT1 ~ log.ros.area*pflower + summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.summer.av.temp.cor.int2 <- glmer(flow.sumT1 ~ log.ros.area + pflower*summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.summer.av.temp.cor.int3 <- glmer(flow.sumT1 ~ log.ros.area*pflower*summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

noflowers.summer.av.temp.cor.trt <- glmer(flow.sumT1 ~ log.ros.area + trt + pflower + summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.summer.av.temp.cor.trt.int1 <- glmer(flow.sumT1 ~ log.ros.area*trt + pflower + summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.summer.av.temp.cor.trt.int2 <- glmer(flow.sumT1 ~ log.ros.area + trt*pflower + summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.summer.av.temp.cor.trt.int3 <- glmer(flow.sumT1 ~ log.ros.area + pflower + trt*summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.summer.av.temp.cor.trt.int4 <- glmer(flow.sumT1 ~ log.ros.area + trt + pflower*summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.summer.av.temp.cor.trt.int5 <- glmer(flow.sumT1 ~ log.ros.area*pflower + trt +  summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.summer.av.temp.cor.trt.int6 <- glmer(flow.sumT1 ~ log.ros.area*pflower + trt*summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.summer.av.temp.cor.trt.int7 <- glmer(flow.sumT1 ~ log.ros.area*trt + pflower*summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.summer.av.temp.cor.trt.int8 <- glmer(flow.sumT1 ~ log.ros.area*summer.mean.temp + pflower*trt  + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.summer.av.temp.cor.trt.int9 <- glmer(flow.sumT1 ~ log.ros.area*summer.mean.temp + pflower + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

#noflowers.summer.av.temp.cor.trt.int10 <- glmer(flow.sumT1 ~ log.ros.area*summer.mean.temp*pflower + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.summer.av.temp.cor.trt.int11 <- glmer(flow.sumT1 ~ log.ros.area + summer.mean.temp*pflower*trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.summer.av.temp.cor.trt.int12 <- glmer(flow.sumT1 ~ log.ros.area*trt*summer.mean.temp + pflower + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.summer.av.temp.cor.trt.int13 <- glmer(flow.sumT1 ~ log.ros.area*pflower*trt + summer.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
##################################

#winter ave temp
noflowers.winter.av.temp <- glmer(flow.sumT1 ~ log.ros.area + winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.int <- glmer(flow.sumT1 ~ log.ros.area*winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

noflowers.winter.av.temp.trt <- glmer(flow.sumT1 ~ log.ros.area + winter.mean.temp + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.trt.int1 <- glmer(flow.sumT1 ~ log.ros.area*winter.mean.temp + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.trt.int2 <- glmer(flow.sumT1 ~ log.ros.area + winter.mean.temp*trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.trt.int3 <- glmer(flow.sumT1 ~ log.ros.area*winter.mean.temp*trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

noflowers.winter.av.temp.cor <- glmer(flow.sumT1 ~ log.ros.area + pflower + winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.int1 <- glmer(flow.sumT1 ~ log.ros.area*pflower + winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.int2 <- glmer(flow.sumT1 ~ log.ros.area + pflower*winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.int3 <- glmer(flow.sumT1 ~ log.ros.area*pflower*winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

noflowers.winter.av.temp.cor.trt <- glmer(flow.sumT1 ~ log.ros.area + trt + pflower + winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.trt.int1 <- glmer(flow.sumT1 ~ log.ros.area*trt + pflower + winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.trt.int2 <- glmer(flow.sumT1 ~ log.ros.area + trt*pflower + winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.trt.int3 <- glmer(flow.sumT1 ~ log.ros.area + pflower + trt*winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.trt.int4 <- glmer(flow.sumT1 ~ log.ros.area + trt + pflower*winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.trt.int5 <- glmer(flow.sumT1 ~ log.ros.area*pflower + trt +  winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.trt.int6 <- glmer(flow.sumT1 ~ log.ros.area*pflower + trt*winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.trt.int7 <- glmer(flow.sumT1 ~ log.ros.area*trt + pflower*winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.trt.int8 <- glmer(flow.sumT1 ~ log.ros.area*winter.mean.temp + pflower*trt  + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.trt.int9 <- glmer(flow.sumT1 ~ log.ros.area*winter.mean.temp + pflower + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

noflowers.winter.av.temp.cor.trt.int10 <- glmer(flow.sumT1 ~ log.ros.area*winter.mean.temp*pflower + trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
#noflowers.winter.av.temp.cor.trt.int11 <- glmer(flow.sumT1 ~ log.ros.area + winter.mean.temp*pflower*trt + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.trt.int12 <- glmer(flow.sumT1 ~ log.ros.area*trt*winter.mean.temp + pflower + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
noflowers.winter.av.temp.cor.trt.int13 <- glmer(flow.sumT1 ~ log.ros.area*pflower*trt + winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")

poisson <- mget(ls(pattern = "^noflowers")) #make a list of all of those models that start with gm (^ means start with)

poisson_AICc<-aictab(cand.set = poisson, modnames = NULL,second.ord=TRUE,nobs=NULL,sort=TRUE)

#rm(list = ls()[grepl("noflowers", ls())])

#best fit model is that - lots of convergence/singular/rank deficient errors

AIC.save.nof <- poisson_AICc %>% 
  arrange(AICc) %>% 
  slice_head(n =10)
AIC.save.nof$vitalrate <- "no.flowers"
AIC.save <- rbind(AIC.save, AIC.save.nof)
```

```{r run best fit model}
noflowers.winter.av.temp <- glmer(flow.sumT1 ~ log.ros.area + winter.mean.temp + (1|plot) + (1|year), data = subset(primula, flow.sumT1 > 0), family = "poisson")
summary(noflowers.winter.av.temp)
```


```{r figures}
pred.dat <- expand.grid(
  log.ros.area = seq(1.5, 6, by = .1), 
  winter.mean.temp = c(-1, 0, 1))
pred.dat.output.n <- cbind(pred.dat, noflowers = predict(noflowers.winter.av.temp, newdata = pred.dat, type = "response", re.form = ~0))

(poisson <- 
  ggplot(subset(primula, !is.na(flow.sumT1) & flow.sumT1>0), aes(x = log.ros.area, y = flow.sumT1))+
  #geom_jitter(height = .05)+
  geom_point(alpha = 0.1) +
  geom_line(data = subset(pred.dat.output.n, winter.mean.temp == -1), aes(x = log.ros.area, y = noflowers), color = "#323697", size = 1.5) +
  geom_line(data = subset(pred.dat.output.n, winter.mean.temp == 1), aes(x = log.ros.area, y = noflowers), color = "#f2623f", size = 1.5) +
  geom_line(data = subset(pred.dat.output.n, winter.mean.temp == 0), aes(x = log.ros.area, y = noflowers), color = "#94c8e0", size = 1.5) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 6))+
  scale_y_continuous(n.breaks = 8) +
  labs(x = "log(Rosette Area) in t", y = "Flowers in t+1")+
    theme(axis.line = element_line(colour = 'black', linewidth = 1.1), text = element_text(size = 20)))

poisson
#ggsave(plot = poisson, file = "C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/Primula/Figures/climate vital rate selection/2no.flowers winter temp.fig.png", width = 5, height = 5, dpi = 300)

```

```{r put all of them together?}
(others <- (survival | pflow | poisson)+plot_annotation(tag_levels = 'A'))
(all <- together/(survival +pflow + poisson) + plot_layout(guides = "collect", axis_titles = "collect") + plot_annotation(tag_levels = list(c("A", "", "", "B", "C", "D")))) 

#ggsave(plot = all, file = "C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/Primula/Figures/climate vital rate selection/all2.png", width = 15, height = 10, dpi = 300)
#ggsave(plot = others, file = "C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/Primula/Figures/climate vital rate selection/vr april 3.png", width = 15, height = 8, dpi = 300)
```

```{r}
#saving AIc table
#write.csv(x = AIC.save, file = "C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/Primula/tables/climate VR AIC/all_AIC.csv")
```


#no.seeds

```{r}
#TO be used in IPM: number of seeds per flower, is this treatment dependent?
#Seeds per flower
#these are for per capita
cap <- glmer(percapseeds~1+(1|plot), data = subset(primula, total.seeds >0), family = "poisson")
cap1 <- glmer(percapseeds~log.ros.area + (1|year) + (1|plot), data = subset(primula, total.seeds >0), family = "poisson")
cap2  <- glmer(percapseeds~log.ros.area+trt + (1|year) + (1|plot), data = subset(primula, total.seeds >0), family = "poisson")
cap3  <- glmer(percapseeds~log.ros.area*trt + (1|year)+ (1|plot), data = subset(primula, total.seeds >0), family = "poisson")
cap4  <- glmer(percapseeds~trt + (1|year)+ (1|plot), data = subset(primula, total.seeds >0), family = "poisson")

capsules <- mget(ls(pattern = "^cap")) #make a list of all of those models that start with gm (^ means start with)
capsule_AICc<-aictab(cand.set = capsules, modnames = NULL,second.ord=TRUE,nobs=NULL,sort=TRUE)
summary(cap4)

pred.dat <- expand.grid(trt = c("control", "irrigated", "drought"))
pred <- predict(cap4, newdata = pred.dat, type="response", re.form=~0) #re.form = ~0 tells it to not include random effects
pred <- as.data.frame(pred)
pred <- cbind(pred.dat, pred)
#flowers in drought plots make 6 seeds, control make 11, irrigated make 13 - this is what we want to use in the IPM

ggplot(data = subset(primula, total.seeds >0), aes(x=trt, y=percapseeds, color = trt))+
  geom_boxplot()

```


